services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rag_app
    ports:
      - "8501:8501"
    volumes:
      - ./src:/app/src
      - ./data:/app/data
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      TAVILY_API_KEY: ${TAVILY_API_KEY} 
      QDRANT_URL: "http://qdrant:6333"
      DATABASE_URL: "postgresql://user:password@postgres:5432/housedata" 
      PYTHONUNBUFFERED: 1
    depends_on:
      - qdrant
      - postgres 
    restart: unless-stopped

  qdrant:
    image: qdrant/qdrant:v1.9.2 
    container_name: qdrant_db
    ports:
      - "6333:6333" 
      - "6334:6334" 
    volumes:
      - ./qdrant_storage:/qdrant/storage 
    restart: unless-stopped

  postgres:
    image: postgres:15
    container_name: postgres_db
    ports:
      - "5432:5432" 
    volumes:
      - postgres_data:/var/lib/postgresql/data 
    environment:
      POSTGRES_DB: housedata 
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password 
    restart: unless-stopped

volumes:
  qdrant_storage: 
  postgres_data: